apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  externalIPs:
  - {{ .Values.externalips }}
  selector:
    app: {{ .Values.appname }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
